import { useEffect, useState } from "react"
import { useSearchParams } from "next/navigation"
import { useRouter } from "next/router"
import styles from '../styles/Counter.module.css'

export default function Counter() {
    const [number, setNumber] = useState(0);
    const searchParams = useSearchParams();
    const isUser = searchParams.get('username');
    const router = useRouter();

    useEffect(() => {
        !isUser ? router.push('/') : <></>
    }, [isUser])

    return (
        <>
            <head>
                <title>Counter Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <main className={styles.main}>
                <body>
                    <div class="counter">
                        <div class="title">Counter Page</div>
                        <div class="user-greet">Welcome {isUser}</div>
                        <div class="counter-box">
                            <div class="num">{number}</div>
                            <div class="buttons">
                                <button onClick={() => setNumber(number + 1)}>Increment</button>
                                <button onClick={() => setNumber(number - 1)}>Decrement</button>
                            </div>
                        </div>
                    </div>
                </body>
            </main>
        </>
    )
}   